### ISSUE TITLE
Scale for the DB view

### ISSUE THREAD

**Issue by derpeter** [voc/voctomix#28]
It would be good to have a scale on the DB view and a marc where clipping starts.

**Comment by MaZderMind** [comment]
One could argue about the use of a scale in the UI anyways. I could imagine that, instead of trying to display an accurate scale which will then still have lot's of delay, it wouldn't be better to just have a 'Signal present' Indicator, like a LED on a Soundcard.

We could add such an indicator to each Source to be able to quickly identify which Sources carries audio.

**Comment by derpeter** [comment]
Delay is not really a problem here. The operator needs to be able to estimate if the input is loud enough / not clipping. It doesn't madder if that is synchronous to anything. On the other hand a signal present indication would make the operator thing everything is fine even if the signal is not usable

**Comment by MaZderMind** [comment]
![screenshot from 2016-01-29 21-14-02](https://cloud.githubusercontent.com/assets/142237/12686980/5368f410-c6cd-11e5-8d5a-74d78e0e4901.png)
