### ISSUE TITLE
Is voctomix alive?

### ISSUE THREAD

**Issue by filiphanes** [voc/voctomix#301]
What is the state of development, usage?

**Comment by MaZderMind** [comment]
Personal Opinion (I don't speak for C3VOC or the Project): I think it is not yet dead (ie it is still used every now and then), but I also don't think there's much development going on.

From my point of view, Covid and Remote/Hybrid Conferences raised he need for much more flexible solutions (ie [OBS Studio](https://obsproject.com/)) which, together with [vdo.ninja](https://vdo.ninja) allows for sophisticated Remote/Hybrid events at the expense of a more complex UI and needing a GPU (however modern CPUs have a decent enough embedded GPU).

In my environment I don't see that remote Speakers / Hybrid Setups will go away anytime soon and I don't see Voctomix gain the necessary flexibility. At the same time, the OBS ecosystem is moving fast and getting better and more complete.

**Comment by krokodilerian** [comment]
As a data point, FOSDEM still runs on voctomix1 (the one packaged in Debian, actually :) ) for 26 rooms in parallel, and we're happy with it (but not with voctomix2, because it doesn't have the TCP ingest we need, #244 ).

**Comment by thomic** [comment]
As a further data point, we just produced FrOSCon and CCCamp 2023 with voc2mix

**Comment by fightling** [comment]
Just to say something from my side: 

I'm currently heavily involved into the development of *OpenTalk* (which is a a/v conferencing system written in *rust*). So I do not have much time to do work here.

But I've learned a lot in the last years and I think I would now rewrite many things in vontomix to make it more flexible - what it never was meant for (as @MaZderMind already said).

So I think the current use case is the one people are still using because it fits their traditional needs since voctomix1.
And voctomix2 is just meant to be an advancement of the first version.

Also I once thought that producing a lot of [documentation](https://github.com/voc/voctomix/blob/main/README.md) would lead others to get involved more heavily.

I may not be the marketing guy but if someone likes to work on issue fixing and would need some consulting, I would be happy to invite you to a chat or talk to help.

Until then: It was nice to see voctomix2 transitions in the camp23 recordings and that everything seemed stable.
But there is also **so much more you can do** with *Transitions* if someone would get interested to build custom ones. Also the *Insertions* never seem to be used which could be fed with outputs from the talk booking. But never mind - maybe it's not that easy ;)

greez

**Comment by Kunsi** [comment]
I'll close this issue, since the recent release of 2.0 very much means voctomix is atleast somewhat alive.
