### ISSUE TITLE
Move (or remove) the "Close" button in the GUI

### ISSUE THREAD

**Issue by baldurmen** [voc/voctomix#79]
The "Close" button is very close to the "Cut" button in the GUI. Using the GUI, I nearly clicked "Close" a few times by mistake trying to cut.

1) Is this button necessary? Normally desktop managers already include close buttons when you open a program in a window

2) If you wish to keep it, could it be placed completely to the right side of the menu, separated from other buttons?

**Comment by saerdnaer** [comment]
@baldurmen can you provide a screenshot?

**Comment by MaZderMind** [comment]
@baldurmen it's a hack because we had issues with the gui getting stuck and we added an option for the operator to quickly restart the gui. We use a custom window-manager which has no buttons. As we don't use the cut functionality, the problem never hit us.

You can easily disable the close-button via a config-option: https://github.com/voc/voctomix/blob/master/voctogui/default-config.ini#L27

I'll leave this ticket open as a reminder, to move the close-button to the right in the toolbar.

**Comment by baldurmen** [comment]
@MaZderMind  thanks! That's very helpful.
